// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1X-kaT4TSLp6EJmhC2qZ7W8KLdl6jEXs',
    appId: '1:703592250162:web:23f1aaea77fb437f9bb52b',
    messagingSenderId: '703592250162',
    projectId: 'neuronote-app-c59e7',
    authDomain: 'neuronote-app-c59e7.firebaseapp.com',
    storageBucket: 'neuronote-app-c59e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgFtslbhq_7k1c0Tm6MiYGkuOY5UkI8VQ',
    appId: '1:703592250162:android:8f488dd2dcfb049b9bb52b',
    messagingSenderId: '703592250162',
    projectId: 'neuronote-app-c59e7',
    storageBucket: 'neuronote-app-c59e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoDj6SuH_9QanDT9KwQ7tq_Jj1KrsB93c',
    appId: '1:703592250162:ios:cbe9d8837550e4d49bb52b',
    messagingSenderId: '703592250162',
    projectId: 'neuronote-app-c59e7',
    storageBucket: 'neuronote-app-c59e7.firebasestorage.app',
    iosBundleId: 'com.example.neuronoteApp',
  );
}
